types:
  definitions:
    default-package: com.palantir.docker.compose.events
    objects:
      Event:
        union:
          build: BuildEvent
          pull: PullEvent
          up: UpEvent
          waitForServices: WaitForServicesEvent
          clusterWait: ClusterWaitEvent
          shutdown: ShutdownEvent

      BuildEvent:
        fields:
          task: Task

      PullEvent:
        fields:
          task: Task

      UpEvent:
        fields:
          task: Task

      WaitForServicesEvent:
        fields:
          task: Task

      ClusterWaitEvent:
        fields:
          task: Task
          serviceNames: list<string>
          type: ClusterWaitType

      ClusterWaitType:
        values:
            - NATIVE
            - USER

      ShutdownEvent:
        fields:
          task: Task

      Task:
        fields:
          startTime: datetime
          endTime: datetime
          failure: optional<string>
